---
version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '05:00'
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
