---
version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '05:00'
    ignore:
      # ignore all GitHub linguist patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
